// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qxxuCzaMP8cv3-QdXxw3ltPd1MDn7rM',
    appId: '1:1000919561145:android:c7b20b35ba32d999e53c68',
    messagingSenderId: '1000919561145',
    projectId: 'project-7053e',
    storageBucket: 'project-7053e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4oN69ljNNQ_5kCRlar_dbwI9oIHacAqQ',
    appId: '1:1000919561145:ios:294d795d0bf54547e53c68',
    messagingSenderId: '1000919561145',
    projectId: 'project-7053e',
    storageBucket: 'project-7053e.appspot.com',
    androidClientId:
        '1000919561145-aa9g34c9ct7ucigo4hm1qe4pgd8rven2.apps.googleusercontent.com',
    iosClientId:
        '1000919561145-0c06hedv74utj1uha65sd0sujepsv1uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.doanQizz',
  );
}
